import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="flex min-h-screen justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-xs rounded overflow-hidden shadow-lg my-2 bg-green-200">
        <div className="px-6 py-4">
          <div className="font-bold text-xl mb-2">Next + Typescript + Tailwind ❤️</div>
        </div>
      </div>
    </div>
  );
};

export default Home;