export const TEMPLATE_SECTION_TITLES: Record<string, Record<string, string>> = {
  modern: {
    work: 'Work Experience',
    involvement: 'Key Projects / Involvements',
    achievements: 'Certificates and Awards',
    summary: 'Summary',
    objective: 'Career Objective',
    tech_expertise: 'Technical expertise',
    skills_exposure: 'Skills / Exposure',
    methodology: 'Practices',
    tools: 'Tools',
    education: 'Education',
    frameworks: 'Frameworks & Libraries',
  },
  professional: {
    work: 'Work Experience',
    involvement: 'Key Projects / Involvements',
    achievements: 'Certificates and Awards',
    summary: 'Summary',
    objective: 'Career Objective',
    tech_expertise: 'Technical expertise',
    skills_exposure: 'Skills / Exposure',
    methodology: 'Practices',
    tools: 'Tools',
    education: 'Education',
  },
  classic: {
    summary: 'Professional Summary',
    objective: 'Career Objective',
    work: 'Work Experience',
    education: 'Education',
    involvement: 'Projects / Involvements',
    achievements: 'Certifications & Achievements',
    awards: 'Awards',
    skills: 'Technical Skills',
  },
  spotlight: {
    work: 'Experience',
    awards: 'Awards',
    methodology: 'Practices',
    tools: 'Tools',
    education: 'Education',
    skills: 'Skills',
  },
};
